name: football_impostor
description: Football Impostor - Adivina el jugador secreto
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.18.0 <4.0.0"
dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.3.0
  google_mobile_ads: ^6.0.0
  in_app_purchase: ^3.0.8
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  audioplayers: ^6.0.0
  flutter_svg: ^2.0.9
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
flutter:
  uses-material-design: true
  assets:
    - assets/players.json
    - assets/hector_logo.svg
    - assets/hector_background.jpg
    - assets/hector_icon.jpg
    - assets/hector_banner.png
    - assets/sounds/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/hector_icon.jpg"
  adaptive_icon_background: "#1B2E28"
  adaptive_icon_foreground: "assets/hector_icon.jpg"

